### ISSUE TITLE
Thắc mắc về việc lấy data

### ISSUE THREAD

**Issue by vanloc1808** [anhdung98/diem_thi_2022#1]
Dạ anh ơi, cho em hỏi anh crawl data bằng cách nào vậy ạ? Em cảm ơn ạ

**Comment by davidtranjs** [comment]
+1 cùng thắc mắc

**Comment by anhdung98** [comment]
Mình có commit source code lên Github rồi nhé, trong file Readme cũng ghi:

> Công cụ Crawl dữ liệu được viết bằng Python Framework [Scrapy](https://github.com/scrapy/scrapy), nguồn dữ liệu thu thập từ trang web [tienphong.vn](https://tienphong.vn/tra-cuu-diem-thi.tpo).
